import { Toaster } from '@/components/ui/sonner';
import RootProvider from '@/components/utils/root-provider';
import { bricolage, wanted } from '@/lib/fonts';
import type { Metadata } from 'next';
import Footer from './footer';
import './globals.css';
import Nav from './nav';

export const metadata: Metadata = {
  title: 'Algorix LLC',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${wanted.variable} ${bricolage.variable}`}>
      <body className="font-sans h-screen w-screen overflow-x-hidden overflow-y-auto">
        <RootProvider>
          <Nav />
          <Toaster />

          {children}

          <Footer />
        </RootProvider>
      </body>
    </html>
  );
}
